services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - .mongo-local-data:/data/db

  frontend:
    image: ghcr.io/joelmeier/nucleus-frontend:latest
    pull_policy: always
    ports:
      - "3000:80"
    depends_on: [ backend ]

  backend:
    image: ghcr.io/joelmeier/nucleus-backend:latest
    pull_policy: always
    depends_on:
      - db
    volumes:
      - /nucleus-backend/calculations:/app/calculations
    environment:
      - MONGO_URI=mongodb://mongo:admin@db:27017
      - CALCULATIONS_PATH=/app/calculations
    ports:
      - "8000:80"

volumes:
  db-data:
