services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - .mongo-local-data:/data/db

  frontend:
    build:
      context: ../nucleus-frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=http://backend:80
    depends_on: [ backend ]

  init-db:
    build:
      context: ../nucleus-backend
    depends_on:
      - db
    volumes:
      - /Users/joelmeier/Docs/fhnw/bachelor-thesis/nucleus-backend/calculations/single_calculation_data:/app/single_calculation_data
    environment:
      - MONGO_URI=mongodb://mongo:admin@db:27017
    entrypoint: [ "sh", "-c", "sleep 5 && python app/parser/comp_parser.py /app/single_calculation_data" ]
    restart: "no"

  backend:
    build:
      context: ../nucleus-backend
    depends_on:
      - db
      - init-db
    volumes:
      - /Users/joelmeier/Docs/fhnw/bachelor-thesis/nucleus-backend/calculations/:/app/calculations
    environment:
      - MONGO_URI=mongodb://mongo:admin@db:27017
      - CALCULATIONS_PATH=/app/calculations
    ports:
      - "8000:80"

volumes:
  db-data:
